MARP-1703 end2 end testing tryout with adding a new test to call to real endpoint
axonivy-market/open-weather-connector pull request #35
Opened 2024-12-27 08:17 UTC by ntqdinh-axonivy

2024-12-27 08:55 UTC, ntqdinh-axonivy commented
Hi @ivy-rew 
I have just prepared some new test cases for API testing using the approach we discussed in the previous meeting.
Should we remove old test cases (with mock server) that just check the response status and the instance of results?

2025-01-02 07:04 UTC, ivy-rew commented
> Hi @ivy-rew I have just prepared some new test cases for API testing using the approach we discussed in the previous meeting. Should we remove old test cases (with mock server) that check the response status and the instance of results? For test cases with mock data to test the logic, we think it still need to keep it as it is, right?

Thanks for reaching out.
I'd not remove the old mock-based tests, they still offer value, documenting how the service worked when the features were developed. Furthermore the mock-service can be used for demos ... simply adding the test-project to a workspace allows presales and others to play with the service while being offline.

2025-01-02 07:05 UTC, ivy-rew commented on open-weather-connector/config/variables.yaml
> +    weatherGeoUrl: ""
why did we remove these good defaults? :thinking:  ... AppFixture will override these values, even they are not blank

2025-01-02 07:09 UTC, ivy-rew commented on open-weather-connector-test/src_test/com/axonivy/connector/openweather/test/it/BaseProcessTest.java
> +public class BaseProcessTest {
junit5 should no longer be used with base-classes: normally you'd rather pack such code as in this class in a junit5-extension.
And then add it to each test via @RegisterExtension
![junit5-ext](https://github.com/user-attachments/assets/eec0f9c4-ad25-4f18-9e61-d0e7b524049b)

2025-01-02 07:10 UTC, ivy-rew commented on open-weather-connector-test/src_test/com/axonivy/connector/openweather/test/it/BaseProcessTest.java
> +	protected static final String TEST_ZIPCODE_VALUE = "10001";
I think this class is about setting up the client ... and should not be mixed up with assertions ... I'd rather move this out into a distinct interface.

2025-01-02 07:15 UTC, ivy-rew commented on open-weather-connector-test/src_test/com/axonivy/connector/openweather/test/it/AirPollutionProcessTest.java
> +public class AirPollutionProcessTest extends BaseProcessTest {
seems as if you have duplicated all tests now .... just to run it also towards a real environment?
this seems very hard to maintain to me; shouldn't we better instrument junit5 to run the same tests towards multiple environments? this can be achieved with TestTemplates...
![junit5-templates](https://github.com/user-attachments/assets/ce5af679-ba4c-4c1f-89e2-86628066e701)

2025-01-02 07:16 UTC, ivy-rew reviewed
Good first steps; let's make more of the standard junit5 features to avoid duplication in our tests.... especially as we are sort of gaining experience how to apply the approach for many connectors.

2025-01-02 07:41 UTC, ntqdinh-axonivy commented
Thanks for your hint on our implementation. I would have a try on your suggestion of multiple environments using TestTemplates and update the document soon. :relaxed:

2025-01-02 09:45 UTC, ivy-rew commented
> Thanks for your hint on our implementation. I would have a try on your suggestion of multiple environments using TestTemplates and update the document soon. ☺️

cool, note though that it is just a hint. maybe it's not easy to keep both impls sync ... as the service may changes its outputs. 
another solution could be to parameterize the stuff only at built time.... by passing system-args to the surefire run and planning the same execution twice ... with differen params.

2025-01-08 04:44 UTC, nqhoan-axonivy requested changes
Your approach is very cool and it fits my expectaction. 
But please keep the TAB format for all connector as a conversation of market product.
And I just have one small concern in the code, please help to check it.
Thanks!

2025-01-08 04:44 UTC, nqhoan-axonivy commented on open-weather-connector-test/src/com/axonivy/connector/openweather/test/context/TestEnironmentInvocationContext.java
> +          throws ParameterResolutionException {
aware on format code (mixed TAB and spaces)

2025-01-08 04:44 UTC, nqhoan-axonivy commented on open-weather-connector-test/src/com/axonivy/connector/openweather/test/utils/OpenWeatherUtils.java
> +          appId = (String) props.get(APP_ID_KEY);
can we use Properties#getProperty() method? to avoid cast operator

2025-01-08 09:48 UTC, nqhoan-axonivy approved these changes
LGTM

2025-01-08 18:09 UTC, merged